### ISSUE TITLE
How can i build?

### ISSUE THREAD

**Issue by dominota** [ousttrue/ManglingImgui#1]
Hello Ousttrue,

Please, how can i build your project?

Thanks

**Comment by ousttrue** [comment]
how to create vc solution.

open dll folder by vscode.

or

powershell
```
> cd dll
dll> mkdir build
dll> cd build
dll/build>  & 'C:\Program Files\CMake\bin\cmake' -G "Visual Studio 16 2019" -A x64 ..
```
then build `Project.sln`, output...

* build/Debug/imgui.dll
* build/Release/imgui.dll

MangleImgui require `imgui.dll` in environment variable `PATH`.

for example

/ManglinImGui/.vscode/launch.json

```
"PATH": "${workspaceFolder}\\..\\build\\Debug\\bin" // imgui.dll path
```

**Comment by ousttrue** [comment]
There is a nuget package.

https://www.nuget.org/packages/ManglingImgui

**Comment by dominota** [comment]
Thank you so much @ousttrue

**Comment by dominota** [comment]
I can not install the package from Nuget
I got this error:
`Could not install package 'ManglingImgui 1.0.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`
